dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - python -m unittest
  - pip install coverage codecov
  - coverage run --source pytctl --branch -m unittest discover -v
  - coverage report
  # - bash <(curl -s https://codecov.io/bash)'

# Push the results back to codecov
after_success:
  - codecov
  
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
